let level1;

function loadLevel1() {
    level1 = new Level(
        [
            new PufferFish(),
            new PufferFish(),
            new PufferFish(),
            new PufferFish(),
            new PufferFish(),
            new JellyFish(),
            new JellyFish(),
            new JellyFish(),
            new JellyFish(),
            new JellyFish(),
        ],
        [
            new BubbleItem(),
            new BubbleItem(),
            new BubbleItem(),
            new BubbleItem(),
            new BubbleItem(),
            new BubbleItem(),
            new BubbleItem(),
            new BubbleItem(),
            new BubbleItem(),
            new BubbleItem(),
            new CoinItem(),
            new CoinItem(),
            new CoinItem(),
            new CoinItem(),
            new CoinItem(),
            new CoinItem(),
            new CoinItem(),
            new CoinItem(),
            new CoinItem(),
            new PotionItem(),
            new PotionItem(),
            new PotionItem(),
            new PotionItem(),
            new PotionItem(),
            new PotionItem(),
            new PotionItem(),
            new PotionItem(),
            new PotionItem(),
        ],
        [
            new BackgroundObject('img/3. Background/Layers/5. Water/D2.png', -(720 - 1)),
            new BackgroundObject('img/3. Background/Layers/3.Fondo 1/D2.png', -(720 - 1)),
            new BackgroundObject('img/3. Background/Layers/2. Floor/D2.png', -(720 - 1)),
            new BackgroundObject('img/3. Background/Layers/1. Light/2.png', -(720 - 1)),
            new BackgroundObject('img/3. Background/Layers/5. Water/D1.png', 0),
            new BackgroundObject('img/3. Background/Layers/3.Fondo 1/D1.png', 0),
            new BackgroundObject('img/3. Background/Layers/2. Floor/D1.png', 0),
            new BackgroundObject('img/3. Background/Layers/1. Light/1.png', 0),
            new BackgroundObject('img/3. Background/Layers/5. Water/D2.png', 720 - 1),
            new BackgroundObject('img/3. Background/Layers/3.Fondo 1/D2.png', 720 - 1),
            new BackgroundObject('img/3. Background/Layers/2. Floor/D2.png', 720 - 1),
            new BackgroundObject('img/3. Background/Layers/1. Light/2.png', 720 - 1),
            new BackgroundObject('img/3. Background/Layers/5. Water/D1.png', (720 - 1) * 2),
            new BackgroundObject('img/3. Background/Layers/3.Fondo 1/D1.png', (720 - 1) * 2),
            new BackgroundObject('img/3. Background/Layers/2. Floor/D1.png', (720 - 1) * 2),
            new BackgroundObject('img/3. Background/Layers/1. Light/1.png', (720 - 1) * 2),
            new BackgroundObject('img/3. Background/Layers/5. Water/D2.png', (720 - 1) * 3),
            new BackgroundObject('img/3. Background/Layers/3.Fondo 1/D2.png', (720 - 1) * 3),
            new BackgroundObject('img/3. Background/Layers/2. Floor/D2.png', (720 - 1) * 3),
            new BackgroundObject('img/3. Background/Layers/1. Light/2.png', (720 - 1) * 3),
            new BackgroundObject('img/3. Background/Layers/5. Water/D1.png', (720 - 1) * 4),
            new BackgroundObject('img/3. Background/Layers/3.Fondo 1/D1.png', (720 - 1) * 4),
            new BackgroundObject('img/3. Background/Layers/2. Floor/D1.png', (720 - 1) * 4),
            new BackgroundObject('img/3. Background/Layers/1. Light/1.png', (720 - 1) * 4),
            new BackgroundObject('img/3. Background/Layers/5. Water/D2.png', (720 - 1) * 5),
            new BackgroundObject('img/3. Background/Layers/3.Fondo 1/D2.png', (720 - 1) * 5),
            new BackgroundObject('img/3. Background/Layers/2. Floor/D2.png', (720 - 1) * 5),
            new BackgroundObject('img/3. Background/Layers/1. Light/2.png', (720 - 1) * 5)
        ]
    );
}